### PR TITLE
Fix the expression of metric dimension generating

### LINKED ISSUE #537: The expression of a dimension in metric can't invoke a function.
Consider a metric case
```json
    {
      "name": "RevenueYear",
      "baseObject": "orders",
      "dimension": [
        {
          "name": "PurchaseYear",
          "type": "DATE",
          "isCalculated": false,
          "notNull": false,
          "expression": "date_trunc('YEAR', PurchaseTimestamp)"
        }
      ],
      "measure": [
        {
          "name": "Price",
          "type": "DOUBLE",
          "expression": "sum(order_items.Price)"
        }
      ]
    }
```

The generated SQL is incorrect:
```
"RevenueYear" AS (
   SELECT
     orders.date_trunc('YEAR', PurchaseTimestamp) "PurchaseYear"
   , sum("orders_relationsub"."Price") "Price"
   FROM
     ((
      SELECT *
      FROM
        (
         SELECT *
         FROM
           "orders"
      )  "orders"
   )  "orders"
   LEFT JOIN (
      SELECT
        "orders"."OrderId"
      , "order_items"."Price"
      FROM
        ("orders"
      LEFT JOIN "order_items" ON ("orders"."OrderId" = "order_items"."OrderId"))
   )  "orders_relationsub" ON ("orders"."OrderId" = "orders_relationsub"."OrderId"))
   GROUP BY 1
) 
```

`date_trunc` should not be added prefix.

### PR DESCRIPTION
**Pull request by goldmedal**
fixed #537

### CODE REVIEW

File: wren-base/src/main/java/io/wren/base/sqlrewrite/MetricSqlRender.java [hunk 1]
```diff
@@ -151,21 +151,31 @@ protected String getSelectItemsExpression(Column column, Optional<String> relati
...
+            @Override
+            public Expression rewriteIdentifier(Identifier node, Void context, ExpressionTreeRewriter<Void> treeRewriter)
+            {
+                if (baseModel.getColumns().stream().anyMatch(c -> c.getName().equalsIgnoreCase(node.getValue()))) {
+                    return new DereferenceExpression(new Identifier(baseModel.getName(), true), new Identifier(node.getValue(), true));
+                }
+                return node;
+            }
+        }, expression);
     }
```
Comment (grieve54706) [inline wren-base/src/main/java/io/wren/base/sqlrewrite/MetricSqlRender.java:179]: If they have same pattern to format. how about extract the model string like below:
```java
  String model;
  if (!relationshipInfos.isEmpty() && relationableBase.isPresent()) {
      model = RelationshipRewriter.relationshipAware(relationshipInfos, relationableBase.get(), expression).toString();
  }
  else if (isMeasure) {
      model = awareModel(column.getExpression().orElseThrow(() -> new IllegalArgumentException("measure column must have expression")), baseModel);
  }
  else {
      model = awareModel(column.getSqlExpression(), baseModel);
  }
  return format("%s AS \"%s\"", model, column.getName());
```

**Review by grieve54706 — APPROVED** [review]
LGTM, minor refactor.

File: wren-base/src/main/java/io/wren/base/sqlrewrite/MetricSqlRender.java (hunk 1 above)
Comment (goldmedal) [reply wren-base/src/main/java/io/wren/base/sqlrewrite/MetricSqlRender.java:179]: The return result of awareModel is a written expression. Like `orderkey` would be `Orders.orderkey`. I think that the current way is better.
